services:
  - type: web
    name: your-app-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-postgres-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: HTTPX_DISABLE_PROXIES
        value: "1"

  - type: web
    name: your-app-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://ticket-maker.onrender.com