services:
  - type: web
    name: your-app-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-postgres-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: your-app-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-url.onrender.com 